from django.utils.translation import ugettext as _
CONSULTANCY_CHOICES = ( 
	('ROUTINE', _('ROUTINE')), 
	('INDIVIDUAL', _('INDIVIDUAL')),
	('INSTITUTIONAL',_('INSTITUTIONAL')),
	('CDF',_('CDF')),
       
   
)
LAB_CHOICES = ( 
	('SOM', _('SOM')),
	('SOIL', _('SOIL')),
	('ST.D DESIGN',_('ST.D DESIGN')),
	('CET', _('CET')),
	('ELECTRONIC', _('ELECTRONIC')),
	('IT & COMPUTER', _('IT & COMPUTER')),
	('ELECTRICAL', _('ELECTRICAL')),
	('CIVIL', _('CIVIL')),
	('MECH', _('MECH')),
	('MBA', _('MBA')),
	('MCA', _('MCA')),
	('WORKSHOP', _('WORKSHOP')),
	('CHEMICAL', _('CHEMICAL')),
	('SURVEY', _('SURVEY')),
	('ENVIRONMENT', _('ENVIRONMENT')),
	('COMPUTATION', _('COMPUTATION')),
	('OTHER', _('OTHER')),
)
PAYMENT_CHOICES = ( 
	('CASH', _('CASH')),
	('DD', _('DD')),
	('ONLINE', _('ONLINE')),
	('CHEQUE',_('CHEQUE')),
)
REPORT_TYPE = ( 
	('SUSPENCE', _('SUSPENCE')),
	('GENERAL REPORT', _('GENERAL REPORT')),
	('CDF',_('CDF')),
)
MATERIAL_CHOICES = ( 
	('Material Letter', _('Material Letter')),
	('Letter Received', _('Letter Received')),
)

PREFORMA_CHOICES = ( 
	('PROFORMA BILL', _('PROFORMA BILL')),
	('RECEIPT CDF', _('RECEIPT CDF')),
	('PROFORMA Report', _('PROFORMA Report')),
)
REPORT_CHOICES =( 
	('GENERAL REPORT', _('GENERAL REPORT')),
	('SUSPENCE', _('SUSPENCE')),
	('RECEIPT SUSPENCE', _('RECEIPT SUSPENCE')),
	('RECEIPT GENERAL', _('RECEIPT GENERAL')),
	('RECEIPT CDF', _('RECEIPT CDF')),
	('BILL',_('BILL')),
	('SUSPENCE BILL',_('SUSPENCE BILL')),
	('SUSPENCE CLERENCE REPEORT',_('SUSPENCE CLERENCE REPEORT')),
	('SUSPENCE CLERENCE REPEORT(without Charge)', _('SUSPENCE CLERENCE REPEORT(without Charge)')),
	('OTHER CHARGE BILL',_('OTHER CHARGE BILL')),
	('TRANSPORT BILL',_('TRANSPORT BILL')),
        ('DAILYREPORT',_('DAILYREPORT')),
)

ORGANISATION_CHOICES = (
	('GOVERNMENT', _('GOVERNMENT')),
	('SEMI-GOVERNMENT', _('SEMI-GOVERNMENT')),
	('PRIVATE', _('PRIVATE'))
)

FIELD_CHOICES = (
	('CEMENT', _('CEMENT')),
	('STEEL', _('STEEL')),
	('BRICKS', _('BRICKS')),
	('MIX DESIGN', _('MIX DESIGN')),
	('CUBES', _('CUBES')),
	('PAVER', _('PAVER')),
	('BM/PC', _('BM/PC')),
	('PC', _('PC')),
	('ABC', _('ABC')),
	('TILES', _('TILES')),
	('BM', _('BM')),
	('BITUMAN', _('BITUMAN')),
	('PC', _('PC')),
	('WOOD', _('WOOD')),
	('CONCRETE PAVERS', _('CONCRETE PAVERS')),
	('SOIL/SAND', _('SOIL/SAND')),
	('SOIL SAMPLES', _('SOIL SAMPLES')),
	('COARSE AGGREGATES', _('COARSE AGGREGATES')),
	('OHSRS', _('OHSRS')),
	('SOIL FOR BC', _('SOIL FOR BC')),
	('SURVEY', _('SURVEY')),
	('SAND', _('SAND')),
	('FINE AGGREGATES', _('FINE AGGREGATES')),
	('COARSE & FINE AGGREGATES', _('COARSE & FINE AGGREGATES')),
	('C. AGG. & F. AGG(DEL. MATERIAL)', _('C. AGG. & F. AGG(DEL. MATERIAL)')),
	('C. AGG. (DEL. MATERIAL)', _('C. AGG. (DEL. MATERIAL)')),
	('F. AGG. (DEL. MATERIAL)', _('F. AGG. (DEL. MATERIAL)')),
	('ST.D (OHSR)', _('ST.D (OHSR)')),
	('HAMMER', _('HAMMER')),
	('ST.D (BUILDING)', _('ST.D (BUILDING)')),
	('ST.D (BRIDGE)', _('ST.D (BRIDGE)')),
	('DRINKING WATER', _('DRINKING WATER')),
	('SEWAGE', _('SEWAGE')),
	('CABLE TESTING', _('CABLE TESTING')),
	('METER TESTING', _('METER TESTING')),
	('MOTOR TESTING', _('MOTOR TESTING')),
	('6 WEEK TRAINING', _('6 WEEK TRAINING')),
        ('6 WEEK TRAINING', _('6 WEEK TRAINING')),
        ('6 WEEK TRAINING(CAD Modelling and Analysis Using Solid Works)', _('6 WEEK TRAINING(CAD Modelling and Analysis Using Solid Works)')),
        ('6 WEEK TRAINING(Electronic Circuit Design Usin VHDL)', _('6 WEEK TRAINING (Electronic Circuit Design Usin VHDL)')),
	('2 WEEK TRAINING', _('2 WEEK TRAINING')),
	('6 MONTH TRAINING', _('6 MONTH TRAINING')),
	('CRASH COURSE', _('CRASH COURSE')),
	('PRACTICAL', _('PRACTICAL')),
	('DESIGN', _('DESIGN')),
	('DRAWING & DESIGN CHECKING', _('DRAWING & DESIGN CHECKING')),
	('DESIGN CHECKING', _('DESIGN CHECKING')),
	('BRIDGE AND CULVETRS', _('BRIDGE AND CULVETRS')),
	('BUILDINGS', _('BUILDINGS')),
	('WATER AND SEWAGE', _('WATER AND SEWAGE')),
	('OTHER', _('OTHER'))
)

STATES_CHOICES = (
    ('Andhra Pradesh', _('Andhra Pradesh')),
    ('Arunachal Pradesh', _('Arunachal Pradesh')),
    ('Assam', _('Assam')),
    ('Bihar', _('Bihar')),
    ('Chhattisgarh', _('Chhattisgarh')),
    ('Goa', _('Goa')),
    ('Gujarat', _('Gujarat')),
    ('Haryana', _('Haryana')),
    ('Himachal Pradesh', _('Himachal Pradesh')),
    ('Jammu and Kashmir', _('Jammu and Kashmir')),
    ('Jharkhand', _('Jharkhand')),
    ('Karnataka', _('Karnataka')),
    ('Kerala', _('Kerala')),
    ('Madhya Pradesh', _('Madhya Pradesh')),
    ('Maharashtra', _('Maharashtra')),
    ('Manipur', _('Manipur')),
    ('Meghalaya', _('Meghalaya')),
    ('Mizoram', _('Mizoram')),
    ('Nagaland', _('Nagaland')),
    ('Orissa', _('Orissa')),
    ('Punjab', _('Punjab')),
    ('Rajasthan', _('Rajasthan')),
    ('Sikkim', _('Sikkim')),
    ('Tamil Nadu', _('Tamil Nadu')),
    ('Tripura', _('Tripura')),
    ('Uttar Pradesh', _('Uttar Pradesh')),
    ('Uttarakhand', _('Uttarakhand')),
    ('West Bengal', _('West Bengal')),
) 

MONTH_CHOICES = ( 
	('January', _('January')),
	('February', _('February')),
	('March',_('March')),
	('April', _('April')),
	('May', _('May')),
	('June',_('June')),
	('July', _('July')),
	('August', _('August')),
	('September',_('September')),
	('October', _('October')),
	('November', _('November')),
	('December',_('December')),
)
YEAR_CHOICES = ( 
	('2011', _('2011')),
	('2010', _('2010')),
	('2012', _('2012')),
	('2013', _('2013')),
	('2014', _('2014')),
	('2015', _('2015')),
	('2016', _('2016')),
	('2017', _('2017')),
	('2018', _('2018')),
	('2019', _('2019')),
	('2020', _('2020')),
	('2021', _('2021')),
)

DAY_CHOICES = ( 
	('01', _('01')),
	('02', _('02')),
	('03', _('03')),
	('04', _('04')),
	('05', _('05')),
	('06', _('06')),
	('07', _('07')),
	('08', _('08')),
	('09', _('09')),
	('10', _('10')),
	('11', _('11')),
	('12', _('12')),
	('13', _('13')),
	('14', _('14')),
	('15', _('15')),
	('16', _('16')),
	('17', _('17')),
	('18', _('18')),
	('19', _('19')),
	('20', _('20')),
	('21', _('21')),
	('22', _('22')),
	('23', _('23')),
	('24', _('24')),
	('25', _('25')),
	('26', _('26')),
	('27', _('27')),
	('28', _('28')),
	('29', _('29')),
	('30', _('30')),
	('31', _('31')),
)
DAILY_CHOICES = ( 
	('CASH', _('CASH')),
	('CHEQUE/DD/ONLINE',_('CHEQUE/DD/ONLINE')),
)
